name: Mirror A -> B (SSH)

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # <--- muy importante: clona todo el historial

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MIRROR_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Push to substitucions
        run: |
          git remote add mirror git@github.com:paraproxectos-ctrl/substitucions.git || true
          git push --force --tags mirror main   # <-- añadimos --tags para llevar todo
