name: Mirror A -> B (SSH)

on:
  push:
    branches: [ main ]   # <-- cambia si tu rama principal NO es main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo A
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set git identity
        run: |
          git config user.name "repo-sync-bot"
          git config user.email "actions@github.com"

      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Trust github.com host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Add remote (idempotent) and test access
        run: |
          set -e
          git remote remove mirror || true
          git remote add mirror git@github.com:paraproxectos-ctrl/substitucions.git
          git remote -v
          git ls-remote --heads mirror

      - name: Push main -> main (force)
        run: |
          git push mirror main:main --force
