name: Mirror A -> B (SSH)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout A (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # evita errores de 'index-pack failed'

      - name: Add github.com to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MIRROR_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          git config --global user.name "mirror-bot"
          git config --global user.email "mirror-bot@users.noreply.github.com"

      - name: Add remote B
        run: |
          git remote add mirror git@github.com:paraproxectos-ctrl/substitucions.git
          git fetch mirror --prune

      - name: Push mirror (force main + tags)
        run: |
          git gc --prune=now
          git push --force mirror HEAD:refs/heads/main
          git push --force --tags mirror
