name: Mirror A -> B (SSH)

on:
  push:
    branches:
      - main   # <-- si tu rama en A es 'master', cambia aquí y más abajo

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MIRROR_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Push to substitucions
        run: |
          git remote add mirror git@github.com:paraproxectos-ctrl/substitucions.git || true
          git push --force mirror main
