name: Sync to substitucions

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: sync-to-substitucions
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      TARGET_OWNER: paraproxectos-ctrl
      TARGET_REPO: substitucions
      TARGET_BRANCH: main

      RSYNC_EXCLUDES: |
        --exclude ".git/"
        --exclude ".github/"
        --exclude "node_modules/"
        --exclude ".env"
        --exclude ".env.*"
        --exclude ".netlify/"
        --exclude "netlify/"
        --exclude "netlify.toml"
        --exclude ".netlify.toml"
        --exclude "Netlify.toml"
        --exclude "_redirects"
        --exclude "target/"        # ¡evita el bucle!

    steps:
      - name: Checkout source (valente-substitucions)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Clone target (substitucions)
        run: |
          git clone --depth=1 "https://${{ secrets.PUSH_TOKEN }}@github.com/${TARGET_OWNER}/${TARGET_REPO}.git" target
          cd target
          git checkout ${TARGET_BRANCH}

      - name: Copy project (skip excluded; don't copy target itself)
        run: |
          set -e
          rsync -av ${RSYNC_EXCLUDES} ./ target/

      - name: Commit & push if changes (force correct remote)
        run: |
          set -e
          cd target
          git remote set-url origin "https://${{ secrets.PUSH_TOKEN }}@github.com/${TARGET_OWNER}/${TARGET_REPO}.git"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "chore: full sync from valente-substitucions ($(date -u +'%Y-%m-%d %H:%M:%S UTC'))"
            git push origin ${TARGET_BRANCH}
          else
            echo "No hay cambios que sincronizar."
          fi
