name: Sync to substitucions

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ORIGIN
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to DEST main
        env:
          TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          git remote add mirror "https://${TOKEN}@github.com/paraproxectos-ctrl/substitucions.git" || git remote set-url mirror "https://${TOKEN}@github.com/paraproxectos-ctrl/substitucions.git"
          git push --force mirror main:main
